title: TimiVietnam
email: admin@timistudio.dev
description: >- # this means to ignore newlines until "baseurl:"
  Hello everybody!  
  We are team UI/UX and Developer React Native & Flutter.  
  Please bookmark this link to see more items and new updated [codecanyon]: https://codecanyon.net/user/timistudio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://timivietnam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: timivietnam
github_username: timivietnam
author: "TimiVietnam"

rss: "/feed.xml"

# Build settings
theme: jekyll-theme-persephone
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# The settings of comments.
comment:
  enabled: true
  provider: disqus
  disqus:
    name: timivietnam
smiley:
  enabled: true
  dir: img/smileys

# The followings are settings for displays of your blog.
theme_setting:
  slides_count: 5
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    -
      title: "Portfolio"
      url: "https://codecanyon.net/user/timistudio/portfolio"
